use Test;

FOREIGN KEY (WorkerID) REFERENCES Workers(WorkerID) ON DELETE CASCADE ON UPDATE CASCADE
FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY (AddressID) REFERENCES Addres(AddresID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ShiftID) REFERENCES WorkDays(WorkDaysID) ON DELETE CASCADE ON UPDATE CASCADE
	    FOREIGN KEY (GuestID) REFERENCES BookingGuest(GuestID) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE Worker 
